# This workflow can be used to push an image off a branch to Docker Hub.
# This is useful to deploy changes from any branch/PR to BookBrainz beta or test for testing.
name: Push development Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag (Version)'
        required: true
        default: 'beta'

jobs:

  dev:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        continue-on-error: true

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build development image
        run: |
          docker build \
            --target bookbrainz-prod \
            --tag metabrainz/bookbrainz:"${{ github.event.inputs.tag }}" \
            --build-arg DEPLOY_ENV="${{ github.event.inputs.tag }}" \
            --build-arg GIT_COMMIT_SHA="${{ github.sha }}" .
      - name: Push development image
        run: docker push metabrainz/bookbrainz:"${{ github.event.inputs.tag }}"
